services:
  main-db:
    image: 'postgres'
    container_name: 'main-database-container-lab10'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
      - "2345:5432"

  test-db:
    image: 'postgres'
    container_name: 'test-database-container-lab10'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
      - "2346:5432"
